import Image from "next/image";
import Head from "next/head";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Main from "@/components/Main";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Flashloan Trading</title>
        <meta name="description" content="Generated by next framework"></meta>
        <link rel="icon" href="/favicon.ico"></link>
      </Head>
      <Header />
      <Main /> 
      <Footer />
    </div>
  );
}
